/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MMC
 */
import java.io.*;
import com.sun.speech.freetts.*;
import com.sun.glass.events.KeyEvent;
import java .sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax .swing.*;

public class Login_panel extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form Login_panel
     */
    public Login_panel() {
        initComponents();
        conn=javaconnect.connDB();
        //Fillcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    /**
    private void Fillcombo(){
    try{
    String Sql="SELECT * FROM `user_login`";
    pst=conn.prepareStatement(Sql);
    rs=pst.executeQuery();
    while(rs.next()){
    String user_type=rs.getString("user_type");
    combo.addItem(user_type);
    }
    }catch(Exception en){
    JOptionPane.showMessageDialog(null, en);}
    finally {
    try{
    rs.close();
    pst.close();
    
    }catch(Exception e){
    
    JOptionPane.showMessageDialog(rootPane, e);}
    
    
    }
    
    
    
    }
    **/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        combo = new javax.swing.JComboBox();
        txt_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AJ soft [Login Panel]");
        setIconImage(new ImageIcon("logo2.png").getImage());
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(250, 220, 66, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 280, 58, 40);

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txt_username);
        txt_username.setBounds(330, 220, 180, 40);

        combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select User Type", "Admin", "User" }));
        combo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo);
        combo.setBounds(330, 340, 180, 30);

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txt_password);
        txt_password.setBounds(330, 280, 180, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/key_small.png"))); // NOI18N
        jButton1.setText("Login");
        jButton1.setAlignmentX(0.5F);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 405, 130, 40);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lock-512.png"))); // NOI18N
        jLabel4.setAlignmentX(0.5F);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 10, 780, 190);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/google-play-bg.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(799, 504));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static final String Voicename="kevin16";
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String tmp=(String)combo.getSelectedItem();
        String sql="SELECT * FROM `user_login` where user_name=? and user_type=? and user_password=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_username.getText());
            
            pst.setString(3, txt_password.getText());
            pst.setString(2, tmp);
            rs=pst.executeQuery();
            if(rs.next()){
                //JOptionPane.showMessageDialog(null, "username and password is correct");
                rs.close();
                pst.close();
                if(tmp.equals("User")){
                emp_test emp=new emp_test();
                Voice voice;
        VoiceManager vm=VoiceManager.getInstance();
        voice=vm.getVoice(Voicename);
        voice.allocate();
        try {
        voice.speak(txt_username.getText());
        
        }catch(Exception E){}
        
        
                this.setVisible(false);
                emp.setVisible(true);
                }
                else
                {
                Admin_panel adm=new Admin_panel();
                Voice voice;
        VoiceManager vm=VoiceManager.getInstance();
        voice=vm.getVoice(Voicename);
        voice.allocate();
        try {
        voice.speak("hello "+txt_username.getText());
        
        }catch(Exception E){}
        
        
                this.setVisible(false);
                adm.setVisible(true);
                }

            }
            else{
                JOptionPane.showMessageDialog(null, "username and password is not correct");

            }
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
            finally {
    try{
    rs.close();
    pst.close();
    
    }catch(Exception e){
    
    JOptionPane.showMessageDialog(rootPane, e);}
    
    
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        try{
            String tmp=(String)combo.getSelectedItem();
        }catch(Exception E){}
    }//GEN-LAST:event_comboPopupMenuWillBecomeInvisible

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        String tmp=(String)combo.getSelectedItem();
        String sql="SELECT * FROM `user_login` where user_name=? and user_type=? and user_password=?";
        try{
            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_username.getText());
            
            pst.setString(3, txt_password.getText());
            pst.setString(2, tmp);
            rs=pst.executeQuery();
            if(rs.next()){
                //JOptionPane.showMessageDialog(null, "username and password is correct");
                rs.close();
                pst.close();
                if(tmp.equals("User")){
                emp_test emp=new emp_test();
                this.setVisible(false);
                emp.setVisible(true);
                }
                else
                {
                Admin_panel adm=new Admin_panel();
                this.setVisible(false);
                adm.setVisible(true);
                }

            }
            else{
                JOptionPane.showMessageDialog(null, "username and password is not correct");

            }
        }
        catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

        }
            finally {
    try{
    rs.close();
    pst.close();
    
    }catch(Exception e){
    
    JOptionPane.showMessageDialog(rootPane, e);}
    
    
    }
        
        
        
        
        
        
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/key-rot.png")));
        
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/key_small.png")));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
